on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          export JAVA_HOME=$JAVA_HOME_25_X64
          javac Main.java
          java Main